rango/urls.py
from django.urls import path
from django.conf.urls import url
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('product/<slug:product_name_slug>/', views.show_product, name='show_product'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('buyer-my-account/', views.buyer_my_account, name='buyer_my_account'),
    path('cart/', views.cart, name='cart'),
    path('payment/', views.payment, name='payment'),
    path('seller-my-account/', views.seller_my_account, name='seller_my_account'),
    path('upload-product/', views.upload_product, name='upload_product'),
    path('remove-product/', views.remove_product, name='remove_product'),
    path('product-search/', views.product_search, name='product_search'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    NAME_MAX_LENGTH = 128
    CHAR_MAX_LENGTH = 128
    id = models.CharField(max_length=CHAR_MAX_LENGTH, primary_key=True)
    name = models.CharField(max_length=CHAR_MAX_LENGTH, unique=True)
    slug = models.SlugField(unique=True)
    sales = models.IntegerField(default=0)
    picture = models.ImageField(upload_to='product_images', blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Product(models.Model):
    CHAR_MAX_LENGTH = 128
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    id = models.CharField(max_length=CHAR_MAX_LENGTH, primary_key=True)
    name = models.CharField(max_length=CHAR_MAX_LENGTH, unique=True)
    description = models.FileField(upload_to='product_description', blank=True)
    price = models.FloatField(default=0)
    sales = models.IntegerField(default=0)
    slug = models.SlugField(blank=True)
    picture = models.ImageField(upload_to='product_images', blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


        
class Cart(models.Model):
    CHAR_MAX_LENGTH = 128
    buyer_name = models.CharField(max_length=CHAR_MAX_LENGTH, default='')
    product_name = models.CharField(max_length=CHAR_MAX_LENGTH, default='')

    def __str__(self):
        return self.buyer_name + self.product_name


class Review(models.Model):
    DESCRIPTION_MAX_LENGTH = 1000
    CHAR_MAX_LENGTH = 128
    buyer_name = models.CharField(max_length=CHAR_MAX_LENGTH, default='')
    product_name = models.CharField(max_length=CHAR_MAX_LENGTH, default='')
    content = models.TextField(default='')

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    CHAR_MAX_LENGTH = 128
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # The additional attributes we wish to include.
    address = models.CharField(max_length=CHAR_MAX_LENGTH, default='', blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    usertype = models.CharField(max_length=CHAR_MAX_LENGTH, default='')

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, UserProfile, Product

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class ProductForm(forms.ModelForm):
    id = forms.CharField(max_length=Product.CHAR_MAX_LENGTH, help_text="Please input the ID of the product.")
    picture = forms.ImageField(required=True, help_text="Please upload the picture of the product.")
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True, empty_label=None, initial="--", help_text="Please enter the category of the product.")
    name = forms.CharField(max_length=Product.CHAR_MAX_LENGTH, help_text="Please enter the name of the product.")
    description = forms.FileField(required=True, help_text="Please upload the description file of the product.")
    price = forms.FloatField(help_text="Please enter the price of the product.")
    sales = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Product

        fields = ('id','picture','category', 'name', 'description', 'price')
        # or specify the fields to include (don't include the category field).
        #fields = ('title', 'url', 'views')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('address','picture', 'usertype',)

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from rango.models import Category, Product, Cart
from rango.forms import CategoryForm, UserForm, UserProfileForm, ProductForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime


def index(request):
    category_list = Category.objects.order_by('-sales')[:5]
    product_list = Product.objects.order_by('-sales')[:5]

    context_dict = {}
    context_dict['categories'] = category_list
    context_dict['products'] = product_list

    visitor_cookie_handler(request)
    # context_dict['visits'] = request.session['visits']
    response = render(request, 'rango/index.html', context=context_dict)
    return response


def show_category(request, category_name_slug):

    context_dict = {}

    category_list = Category.objects.all()

    try:
        category = Category.objects.get(slug=category_name_slug)

        products = Product.objects.filter(category=category)

        context_dict['products'] = products
        context_dict['category'] = category
        context_dict['categories'] = category_list
    except Category.DoesNotExist:

        context_dict['category'] = None
        context_dict['products'] = None
        context_dict['categories'] = None

    return render(request, 'rango/category.html', context=context_dict)



def show_product(request, product_name_slug):

    context_dict = {}

    product_list = Product.objects

    try:
        product = Product.objects.get(slug=product_name_slug)

        # products = Product.objects.filter(category=category)

        # context_dict['products'] = products
        context_dict['product'] = product
        # context_dict['products'] = category_list
    except Category.DoesNotExist:

        context_dict['product'] = None
        # context_dict['produucts'] = None
        # context_dict['categories'] = None

    return render(request, 'rango/product.html', context=context_dict)


@login_required
def add_category(request):

    form = CategoryForm()
    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():

            form.save(commit=True)

            return redirect(reverse('rango:index'))
        else:

            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})



@login_required
def upload_product(request):
   
    form = ProductForm()

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)

        if form.is_valid():

            product = form.save(commit=True)
            product.save()

            return redirect(reverse('rango:seller_my_account'))
        else:
            print(form.errors)

    context_dict = {'form': form}
    return render(request, 'rango/upload_product.html', {'form': form})


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']
            
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
    
    return render(request, 'rango/register.html', context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'rango/login.html')


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits


@login_required
def buyer_my_account(request):
    return render(request, 'rango/buyer_my_account.html')


@login_required
def seller_my_account(request):
    return render(request, 'rango/seller_my_account.html')


@login_required
def cart(request):
    products = Product.objects.all()
    carts = Cart.objects.all()
    username = request.user.username
    product_list = []
    for item in carts:
        if item.buyer_name == username:
            for p in products:
                if item.product_name == p.name:
                    product_list.append(p)

    context_dict = {'products': product_list}
    return render(request, 'rango/cart.html',context=context_dict)


@login_required
def payment(request):
    context_dict = {'user': request.user}
    return render(request, 'rango/payment.html', context=context_dict)


@login_required
def remove_product (request):
    context_dict = {}
    context_dict['products'] = Product.objects.all()
    return render(request, 'rango/remove_product.html',context=context_dict)


def product_search (request):
    context_dict = {}
    context_dict['products'] = Product.objects.all()
    context_dict['categories'] = Category.objects.all()
    return render(request, 'rango/product_search.html', context=context_dict)

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
	<head>
        <meta charset="UTF-8">
        
        <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" media ='all'>
        <link rel='shortcut icon' href="{% static 'images/favicon.ico' %}" type='image/x-icon'/>
        <title>
            {% block title_block %}
            {% endblock %}
        </title>
        
	</head>
	

	<body>
        <div id = "header">
            <img class ='logo' src="{% static 'images/logo.png' %}" alt="Picture of Logo" /> 
            <span class ='title'>Online Shopping Mall  </span>
            <div class="homepage">
                <img  src="{% static 'images/homepage_icon.png' %}" alt="Picture of Homepage_icon" />
                <a class='home' href="{% url 'rango:index' %}">Homepage</a>
            </div>
            <meta charset="UTF-8">
            <link rel="stylesheet" href="{% static 'css/userbase.css' %}" type="text/css" media ='all'>
            <div >
                <input type="search" class ='searchinput'/>
                <a href="{% url 'rango:product_search' %}" class ='searchimg'>
                   
                        <img src="{% static 'images/search.png' %}" alt="Picture of Search" type="search"/>
                    
                </a>
            </div>
            <div class = 'nav'>
                {% if user.is_authenticated %}

                    {% if user.userprofile.usertype == 'Buyer' %}
                        <div class="user_b">  
                            <div class="logout">
                                <a href="{% url 'rango:logout' %}" >Logout</a>
                            </div> 
                            <a href="{% url 'rango:cart' %}" ><img src="{% static 'images/cart_icon.png' %}" alt="Picture of Cart_icon" class = 'cart'/></a>                 
                            <a href="{% url 'rango:buyer_my_account' %}"><img src="{% static 'images/user_icon.png' %}" alt="Picture of User_icon" /></a>
                        </div> 

                    {% else %}
                        <div class="user_s">
                            <div class="logout">
                            <a href="{% url 'rango:logout' %}" >logout</a>
                            </div>
                                <a href="{% url 'rango:seller_my_account' %}"><img src="{% static 'images/user_icon.png' %}" alt="Picture of User_icon" /></a> 
                        </div>
                    {% endif %}
                {% else %}
                    <div class="notuser">
                        <div class="button_login"><a href="{% url 'rango:login' %}" >login</a></div>
                        <div class="button_reg"><a href="{% url 'rango:register' %}">register</a></div>          
                    </div>
                {% endif %}
            </div>






        </div> 

        <div>
            {% block body_block %}
            {% endblock %}
        </div>
	</body>
</html>

templates/rango/buyer_base.html
{% extends 'rango/userbase.html' %}
{% load staticfiles %}

{% block title_block %}
{% endblock %}

{% block userbase_body_block %}   
    {% block buyerbase_body_block %}
    {% endblock %}

    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/buyer_base.css' %}" type="text/css" media ='all'>
    <body>
    <div id="nav">
        <ul>

            <li><a href="{% url 'rango:buyer_my_account' %}">My Account</a></li>
            <li><a href="{% url 'rango:cart' %}">Cart</a></li>
            <li><a href="{% url 'rango:payment' %}">Payment</a></li>

        </ul>
    </div>
</body>    
{% endblock %}

templates/rango/buyer_my_account.html
<!-- <style>
    .userprofile{
        position:absolute;
        top:150px;
        left:780px;
        display:block;

    }
    img.uimg{
        width:100px;
        height:100px;
        border-radius: 50px;
    }
    .uname{
        position:absolute;
        top:400px;
        left:670px;
    }
    .uea{
        position:absolute;
        top:400px;
        left:670px;
        margin: 0;
        padding: 0;
        width: 332px;
        position: fixed;
    }
    .uea li{

        text-align: center;
        list-style: none;
        justify-content: center;
        margin-bottom:15px;
        
    }

    .uea li a {

        font-size:16px;
        color: #000;
        font-weight: bold;
    }

    .utype{
        position:absolute;
        top:700px;
        left:780px;
        font-size:16px;
        color: #000;
        font-weight: bold;
    }

    .br1{
        background-color: rgb(153,135,108,0.7);
        position:absolute;
        top:300px;
        left:330px;
        width:80%;
        height:50px;
    }

    .br1 a{
        color:#99876c;
        width:80%;
        height:50px;
    }

    .br2{
        background-color: rgb(153,135,108,0.7);
        position:absolute;
        top:600px;
        left:330px;
        width:80%;
        height:50px;
    }

    .br2 a{
        color:#99876c
    }
</style> -->
{% extends 'rango/buyer_base.html' %}
{% load staticfiles %}

{% block title_block %}
    My Account
{% endblock %}

{% block buyerbase_body_block %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/account.css' %}" type="text/css" media ='all'>
    
    <div class="userprofile">
        <img src="{{ MEDIA_URL }}{{user.userprofile.picture}}" alt="Picture of Buyer"  class="uimg"/>   
    </div>
    
    
    <div class="uname">
        <ul class="uea">
        <li><a>Username:  {{user.username}}</a></li>
        <li><a>Email:  {{user.email}}</a></li>
        <li><a>Address:  {{user.userprofile.address}}</a></li>
        </ul>
    </div>
    <div class="br2">
        <a></a>
    </div>


    <div class="utype">
        User Type:  {{user.userprofile.usertype}}
    </div>
    
{% endblock %}

templates/rango/cart.html
{% extends 'rango/buyer_base.html' %}
{% load staticfiles %}

{% block title_block %}
    Cart
{% endblock %}

{% block buyerbase_body_block %}

    <div>

        {% if products %}
            <ul>
                {% for p in products %}

                <li>
                    <input type="checkbox"  checkbox="checkbox"/>
                    <a href="{% url 'rango:show_product' p.slug %}"> <img src="{{ MEDIA_URL }}{{ p.picture}}" alt="Picture of Product" />  </a><br/>
                    <a href="{% url 'rango:show_product' p.slug %}">Name : {{ p.name }}</a><br/>
                    <a href="{% url 'rango:show_product' p.slug %}">Description : {{ p.description }}</a><br/>
                    <span>Price : ￡ {{p.price}}</span><br/>
    
                </li>

                {% endfor %}
            </ul>
            
        {% else %}

            <span>There is no product in your cart.</span>

        {% endif %}

            <span>Total : ￡</span><span>153.94</span>
            <input type="submit" value="Check Out" />
        
    </div>

{% endblock %}

templates/rango/categories.html
<ul>
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
            <li>
            <strong>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </strong>
            </li>
            {% else %}
            <li>
                <a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
            </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/buyer_base.html' %}
{% load rango_template_tags %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block userbase_body_block %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/category.css' %}" type="text/css" media ='all'>
    {% if category %}
        {% if products %}
        <ul class = "list1">
            {% for product in products %}
            <li >
                <a href="{% url 'rango:show_product' product.slug %}"> <img src="{{ MEDIA_URL }}{{ product.picture}}" alt="Picture of Product" class = 'proimg'/> </a><br/>
                <a href="{% url 'rango:show_product' product.slug %}" class='name'>{{ product.name }}</a><br/>
                <a href="{% url 'rango:show_product' product.slug %}" class="description">{{ product.description }}</a><br/>
                <a class='price'>£：{{ product.price }}</a>
                <hr />
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No product currently in category.</strong>
        {% endif %}
    {% else %}
        The specified category does not exist.
    {% endif %}
   
    <div class='navigation'>
        {% if categories %}
            {% for c in categories %}
                {% if c == category %}
                    <li class = 'list'>
                    <strong>
                            <a href="{% url 'rango:show_category' c.slug %}" >{{ c.name }}</a>
                     </strong>
                </li>
                {% else %}
                    <li class = 'list'>
                        <a href="{% url 'rango:show_category' c.slug %}" >{{ c.name }}</a>
                    </li>
                {% endif %}
            {% endfor %}
        {% else %}
            <li class = 'list'><strong>There are no categories present.</strong></li>
        {% endif %}
    </div> 

{% endblock %}

templates/rango/payment.html
{% extends 'rango/buyer_base.html' %}
{% load staticfiles %}

{% block title_block %}
    Payment
{% endblock %}

{% block buyerbase_body_block %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/payment.css' %}" type="text/css" media ='all'>
    <div class = 'userinfo'>
        <a>AAAA</a>
        <!-- User Name : {{user.username}}<br />
        Email : {{user.email}}<br />
        Address : {{user.userprofile.address}}<br />
        Price : ￡ 200<br /> -->
    </div>

    <div class = 'card'>
        Card Number : <input type="text" /><br />
        CVV: <input type="text"  /><br />
        Phone Number : <input type="text"  /><br />
        <input type="submit" value="Submit" /><br />
    </div>
    
{% endblock %}

templates/rango/product.html
{% extends 'rango/userbase.html' %}
{% load rango_template_tags %}
{% load staticfiles %}

{% block title_block %}
    {% if product %}
        {{ product.name }}
    {% else %}
        Unknown Product
    {% endif %}
{% endblock %}

{% block userbase_body_block %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/product.css' %}" type="text/css" media ='all'>
    {% if product %}
        <div class="product"> 
            <img src="{{ MEDIA_URL }}{{ product.picture}}" alt="Picture of Product" class = 'productimg'/><br/>
            <span class = 'pname'>{{ product.name }}</span><br/>
          

            <div class = 'pd'> <span class = 'pdes'> {{product.description}}</span><br/></div>
            <span class = 'pprice'>￡ {{product.price}}</span><br/>

            
            <!-- <input type="text" name="review" value="" size="80" height="40" class = 'previewin'/>
            <div class='r2'><input type="submit" value="Submit Review" class = 'previewsub'/><br/></div> -->

            <!-- <img src="{% static 'images/minus.png' %}" alt="Picture of Minus_icon" class = 'img1'/> 
            <span class ='quality'>Quantity</span>
            <img src="{% static 'images/plus.png' %}" alt="Picture of Plus_icon" class = 'img2'/>  -->

            <div class='adddiv'><a  class = 'add'> Add to Cart</div>
            <div class='buydiv'><a href="{% url 'rango:payment' %}" class = 'buy'>Buy Now</a></div>

        </div>
    {% else %}
        The specified product does not exist.
    {% endif %}


{% endblock %}

templates/rango/product_search.html
{% extends 'rango/userbase.html' %}
{% load rango_template_tags %}
{% load staticfiles %}

{% block title_block %}
    Search
{% endblock %}

{% block userbase_body_block %}
    
    Search

{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/register.css' %}" type="text/css" media ='all'>
    {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="{% url 'rango:login' %}">Login Now</a><br />
    {% else %}
        <strong class = 'tip2'>register here!</strong><br />
        <form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="I agree and Register" class = 'register'/>
        </form>
    {% endif %}
{% endblock %}

templates/rango/remove_product.html
{% extends 'rango/seller_base.html' %}
{% load staticfiles %}

{% block title_block %}
    Remove Product
{% endblock %}

{% block seller_base_body_block %}
    
   <div>
        {% for p in products %}
        <li>
            <input type="checkbox"  checkbox="checkbox"/>
            <a href="{% url 'rango:show_product' p.slug %}"> <img src="{{ MEDIA_URL }}{{ p.picture}}" alt="Picture of Product" />  </a><br/>
            <a href="{% url 'rango:show_product' p.slug %}">{{ p.name }}</a><br/>
            <a href="{% url 'rango:show_product' p.slug %}">{{ p.description }}</a><br/>
            <span>Price : ￡ {{p.price}}</span><br/>
        </li>
        {% endfor %}

        <div>
            <input type="submit" value="Confirm and Remove" />
        </div>

   </div>

{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
    <h1>Restricted Page</h1>
    Since you're logged in, you can see this text!<br />
{% endblock %}

templates/rango/seller_base.html
<!-- <style>

    .body_left {
        padding: 0;
        width: 200px;
        min-height:100%;
        display: inline-block;
        background: #333951;
        font-size: 16px;
        color: #fff;
    }
a{
    display:block;
    width:60px;
}



li {
    text-align: center;
    border-bottom: 1px solid #555;
    list-style: none;
}

ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    width: 25%;
    background-color: #f1f1f1;
    position: fixed;
    height: 100%;
    overflow: auto;
    border: 1px solid #555;
}

li a {
    display: block;
    color: #000;
    padding: 8px 16px;
    text-decoration: none;
}

li a.active {
    background-color: #4CAF50;
    color: white;
}

li a:hover:not(.active) {
    background-color: #555;
    color: white;
}
 
li:last-child {
    border-bottom: none;
}
</style> -->

{% extends 'rango/userbase.html' %}
{% load staticfiles %}

{% block title_block %}
    Homepage
{% endblock %}

{% block userbase_body_block %}
 


    {% block seller_base_body_block %}

    {% endblock %}

    <hr />

    <div>
        <ul>
            <li><a href="{% url 'rango:seller_my_account' %}">My Account</a></li>
            <li><a href="{% url 'rango:upload_product' %}">Upload Product</a></li>
            <li><a href="{% url 'rango:remove_product' %}">Remove Product</a></li>
        </ul>
    </div>
    
{% endblock %}

templates/rango/userbase.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
{% endblock %}

{% block body_block %}

    <!-- <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/userbase.css' %}" type="text/css" media ='all'>
    <div class ='search'>
        <input type="search" class ='searchinput'/>
        <a href="{% url 'rango:product_search' %}" class ='searchbutton'><button type="search" >Search</button></a>
    </div>
    <div class = 'nav'>
        {% if user.is_authenticated %}

            {% if user.userprofile.usertype == 'Buyer' %}
                <div class="user_b">  
                    <div class="logout">
                        <a href="{% url 'rango:logout' %}" >Logout</a>
                    </div> 
                    <a href="{% url 'rango:cart' %}" ><img src="{% static 'images/cart_icon.png' %}" alt="Picture of Cart_icon" class = 'cart'/></a>                 
                    <a href="{% url 'rango:buyer_my_account' %}"><img src="{% static 'images/user_icon.png' %}" alt="Picture of User_icon" /></a>
                </div> 

            {% else %}
                <div class="user_s">
                    <div class="logout">
                    <a href="{% url 'rango:logout' %}" >logout</a>
                    </div>
                        <a href="{% url 'rango:seller_my_account' %}"><img src="{% static 'images/user_icon.png' %}" alt="Picture of User_icon" /></a> 
                </div>
            {% endif %}
        {% else %}
            <div class="notuser">
                <div class="button_login"><a href="{% url 'rango:login' %}" >login</a></div>
                <div class="button_reg"><a href="{% url 'rango:register' %}">register</a></div>          
            </div>
        {% endif %}
    </div> -->

    {% block userbase_body_block %}
    {% endblock %}

{% endblock %}